include(cmake/fetch_library.cmake)

function(add_boost tag)
  fetch_library(boost_config https://github.com/boostorg/config.git ${tag})
  fetch_library(boost_assert https://github.com/boostorg/assert.git ${tag})
  fetch_library(boost_static_assert https://github.com/boostorg/static_assert.git ${tag})
  fetch_library(boost_throw_exception https://github.com/boostorg/throw_exception.git ${tag})
  fetch_library(boost_core https://github.com/boostorg/core.git ${tag})
  fetch_library(boost_align https://github.com/boostorg/align.git ${tag})
  fetch_library(boost_mp11 https://github.com/boostorg/mp11.git ${tag})
  fetch_library(boost_variant2 https://github.com/boostorg/variant2.git ${tag})
  fetch_library(boost_predef https://github.com/boostorg/predef.git ${tag})
  fetch_library(boost_winapi https://github.com/boostorg/winapi.git ${tag})
  fetch_library(boost_system https://github.com/boostorg/system.git ${tag})
  fetch_library(boost_asio https://github.com/boostorg/asio.git ${tag})
endfunction()